### ISSUE TITLE
Dpi fix breaks support on Windows 7

### ISSUE THREAD

**Issue by mtissington** [micdenny/WpfScreenHelper#6]
The fix for DPI support breaks Windows 7.

System.DllNotFoundException: Unable to load DLL 'shcore.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

   at WpfScreenHelper.NativeMethods.GetDpiForMonitor(IntPtr hmonitor, DpiType dpiType, UInt32& dpiX, UInt32& dpiY)

   at WpfScreenHelper.Screen..ctor(IntPtr monitor, IntPtr hdc)

   at WpfScreenHelper.Screen.get_AllScreens()

**Comment by micdenny** [comment]
@FoxPride can you help on this? This is because of #5

**Comment by FoxPride** [comment]
@micdenny @mtissington 
It is not available on Windows 7. Windows 8.1 or newer is required based on [Microsoft's documentation](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getdpiformonitor). 
Possible workaround - always return false for windows versions below 8.1

**Comment by micdenny** [comment]
I was excepting to be backward compatible as we discussed here https://github.com/micdenny/WpfScreenHelper/pull/5#issuecomment-925792078

So I'm thinking we need to try do something to fix this and let this version work with windows 7, otherwise we should unlist the actual version from nuget and push a breaking change version v2.0.0 and advice that only v1 works with win7

**Comment by micdenny** [comment]
[v2.0.0 has been released](https://www.nuget.org/packages/WpfScreenHelper/2.0.0)
